# Generated by Django 2.1.1 on 2018-09-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='班级')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='课程名称')),
                ('score', models.IntegerField(blank=True, verbose_name='学分')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教师姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=50, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='家庭住址')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='手机')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=50, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Teachers', verbose_name='老师'),
        ),
        migrations.AddField(
            model_name='class',
            name='headmaster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Teachers', verbose_name='班主任'),
        ),
        migrations.AddField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='app.Subjects', verbose_name='选修课程'),
        ),
    ]
