# Generated by Django 2.1.1 on 2018-09-25 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180925_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subjects')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students')),
            ],
            options={
                'db_table': 'scores',
            },
        ),
    ]
