# Generated by Django 2.1.1 on 2018-09-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_stucourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stucourse',
            options={'managed': True, 'verbose_name': '成绩', 'verbose_name_plural': '成绩集'},
        ),
    ]
